version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    command: server /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
