version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_REGION=us-east-1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: /bin/sh -c "/usr/bin/init.sh"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./init.sh:/usr/bin/init.sh
